[package]
name = "post-tui"
version = "1.0.1"
edition = "2021"
description = "A professional terminal HTTP API client"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/post-tui"
repository = "https://github.com/raufendro-dev/post-tui"
homepage = "https://github.com/raufendro-dev/post-tui"
keywords = ["tui", "http", "api", "client", "terminal"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
directories = "5.0"
ratatui = "0.26"
reqwest = { version = "0.12", default-features = false, features = ["charset", "http2", "json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread", "time"] }
toml = "0.8"
